import { Link } from 'react-router-dom';

export function Guide() {
  return (
    <div className="flex flex-col items-center gap-8 pt-12 pb-12">
      {/* Hero */}
      <div className="text-center">
        <h1 className="font-display text-4xl font-bold text-text-primary">
          User <span className="text-accent">Guide</span>
        </h1>
        <p className="mt-3 max-w-md text-text-secondary">
          Everything you need to know to find and buy music with TrackHunter.
        </p>
      </div>

      {/* Table of contents */}
      <nav className="max-w-2xl w-full rounded-sm border border-border bg-bg-secondary p-5">
        <h2 className="text-sm font-medium text-text-primary mb-3">On this page</h2>
        <ol className="space-y-1.5 text-sm text-accent list-decimal list-inside">
          <li><a href="#import-spotify" className="hover:underline">Import a Spotify playlist</a></li>
          <li><a href="#import-youtube" className="hover:underline">Import from YouTube</a></li>
          <li><a href="#import-soundcloud" className="hover:underline">Import from SoundCloud & Deezer</a></li>
          <li><a href="#manual-search" className="hover:underline">Manual track search</a></li>
          <li><a href="#understanding-results" className="hover:underline">Understanding your results</a></li>
          <li><a href="#wishlist" className="hover:underline">Using the wishlist</a></li>
          <li><a href="#dj-tips" className="hover:underline">Tips for DJs</a></li>
          <li><a href="#faq" className="hover:underline">Frequently asked questions</a></li>
        </ol>
      </nav>

      {/* Import Spotify */}
      <section id="import-spotify" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          1. Import a Spotify playlist
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            Spotify is the easiest way to import tracks into TrackHunter. You can import public
            playlists, albums, and individual tracks. Here's how:
          </p>
          <ol className="list-decimal list-inside space-y-2 text-text-secondary">
            <li>
              Open Spotify (desktop app or web player) and navigate to the playlist, album or track
              you want to search.
            </li>
            <li>
              Click the <strong className="text-text-primary">three dots (...)</strong> menu, then
              select <strong className="text-text-primary">Share &gt; Copy link to playlist</strong> (or
              album/track).
            </li>
            <li>
              Go to the <Link to="/" className="text-accent hover:underline">TrackHunter search page</Link> and
              paste the link into the text box.
            </li>
            <li>
              Click <strong className="text-text-primary">Search</strong> or
              press <strong className="text-text-primary">Ctrl+Enter</strong>. TrackHunter will extract every
              track from the playlist and search for it across Bandcamp, Beatport, MusicBrainz and Discogs.
            </li>
          </ol>
          <p>
            <strong className="text-text-primary">Note:</strong> Only public playlists are supported.
            If your playlist is set to private, you'll need to change its visibility in Spotify
            settings first. Spotify may occasionally be slow or return errors for some tracks — if
            this happens, try again in a few moments.
          </p>
        </div>
      </section>

      {/* Import YouTube */}
      <section id="import-youtube" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          2. Import from YouTube
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            TrackHunter supports importing tracks from YouTube playlists. Copy the playlist URL from
            your browser's address bar and paste it into the search box. The URL should
            contain <strong className="text-text-primary">list=PL...</strong> in it.
          </p>
          <p>
            <strong className="text-text-primary">Important:</strong> YouTube Mix and Radio
            playlists (auto-generated by YouTube) are not supported because they don't have a fixed
            tracklist. Only user-created playlists with
            a <strong className="text-text-primary">PL...</strong> ID work.
          </p>
        </div>
      </section>

      {/* Import SoundCloud & Deezer */}
      <section id="import-soundcloud" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          3. Import from SoundCloud & Deezer
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            You can also import from SoundCloud sets and Deezer playlists. Simply copy the URL from
            your browser and paste it into the TrackHunter search box. The tracks will be extracted
            and searched automatically.
          </p>
          <p>
            SoundCloud sets work best when the track titles follow the standard
            <strong className="text-text-primary"> Artist - Title</strong> format. If titles are
            non-standard (e.g. just the track name without the artist), results may be less accurate.
          </p>
        </div>
      </section>

      {/* Manual search */}
      <section id="manual-search" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          4. Manual track search
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            Don't have a playlist link? No problem. You can type or paste track names directly into
            the search box. Use the <strong className="text-text-primary">Artist - Title</strong> format,
            one track per line:
          </p>
          <div className="rounded-sm border border-border bg-bg-primary p-4 font-mono text-xs text-text-tertiary">
            Kerri Chandler - Rain (DJ Deep Remix)<br />
            Moodymann - Shades of Jae<br />
            Theo Parrish - Falling Up<br />
            Omar S - Thank You For Letting Me Be Myself
          </div>
          <p>
            You can also upload a <strong className="text-text-primary">CSV</strong> or
            <strong className="text-text-primary"> TXT</strong> file containing your tracklist. Click
            the "Upload CSV / TXT" button below the text box to select your file.
          </p>
        </div>
      </section>

      {/* Understanding results */}
      <section id="understanding-results" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          5. Understanding your results
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            After searching, TrackHunter displays a results page with every track from your playlist.
            Each track shows colored indicators for the platforms where it was found:
          </p>
          <div className="flex flex-wrap gap-3 my-3">
            <span className="rounded-sm border border-platform-bandcamp/30 bg-platform-bandcamp/10 px-3 py-1 text-xs text-platform-bandcamp">
              Bandcamp
            </span>
            <span className="rounded-sm border border-platform-beatport/30 bg-platform-beatport/10 px-3 py-1 text-xs text-platform-beatport">
              Beatport
            </span>
            <span className="rounded-sm border border-platform-musicbrainz/30 bg-platform-musicbrainz/10 px-3 py-1 text-xs text-platform-musicbrainz">
              MusicBrainz
            </span>
            <span className="rounded-sm border border-border bg-bg-secondary px-3 py-1 text-xs text-text-secondary">
              Discogs
            </span>
          </div>
          <p>
            Click on any platform badge to open the track's page on that store in a new tab. From
            there, you can preview, purchase or download the track directly. If a platform badge is
            missing, it means the track wasn't found on that particular store.
          </p>
          <p>
            The results page also shows a progress bar while searches are running. TrackHunter
            searches all platforms simultaneously, so results appear as they're found — you don't
            need to wait for everything to finish before you start browsing.
          </p>
        </div>
      </section>

      {/* Wishlist */}
      <section id="wishlist" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          6. Using the wishlist
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            Found a track you want to come back to later? Add it to your wishlist. From the results
            page, click the heart icon next to any track to save it. You can view all your saved
            tracks on the <Link to="/wishlist" className="text-accent hover:underline">Wishlist page</Link>.
          </p>
          <p>
            Your wishlist is stored locally in your browser, so it persists between sessions. No
            account or login is required. Note that clearing your browser data will also clear your
            wishlist.
          </p>
        </div>
      </section>

      {/* DJ tips */}
      <section id="dj-tips" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          7. Tips for DJs
        </h2>
        <div className="mt-4 space-y-3 text-sm text-text-secondary leading-relaxed">
          <p>
            TrackHunter was built with DJs in mind. Here are some workflows to get the most out of
            it:
          </p>
          <div className="space-y-4">
            <div className="rounded-sm border border-border bg-bg-secondary p-4">
              <h3 className="text-sm font-medium text-text-primary">From a tracklist to your collection</h3>
              <p className="mt-1 text-xs text-text-tertiary leading-relaxed">
                Heard a great set on a podcast or livestream? Find the tracklist (often posted in the
                description or comments), paste it into TrackHunter, and buy every track you want on
                Beatport or Bandcamp. This is the fastest way to build your library from mixes you love.
              </p>
            </div>
            <div className="rounded-sm border border-border bg-bg-secondary p-4">
              <h3 className="text-sm font-medium text-text-primary">Spotify to Beatport workflow</h3>
              <p className="mt-1 text-xs text-text-tertiary leading-relaxed">
                Many DJs discover music on Spotify but need to buy high-quality files for their sets.
                Create a "To Buy" playlist on Spotify, add tracks as you discover them, then
                periodically paste the playlist into TrackHunter to find everything on Beatport in one
                go.
              </p>
            </div>
            <div className="rounded-sm border border-border bg-bg-secondary p-4">
              <h3 className="text-sm font-medium text-text-primary">Support artists on Bandcamp</h3>
              <p className="mt-1 text-xs text-text-tertiary leading-relaxed">
                Artists receive a much larger share of revenue from Bandcamp sales compared to
                streaming. Use TrackHunter to check if a track is available on Bandcamp before buying
                it elsewhere — it's a simple way to put more money in the artist's pocket.
              </p>
            </div>
            <div className="rounded-sm border border-border bg-bg-secondary p-4">
              <h3 className="text-sm font-medium text-text-primary">Configure your platforms</h3>
              <p className="mt-1 text-xs text-text-tertiary leading-relaxed">
                If you only buy from certain stores, head to
                the <Link to="/settings" className="text-accent hover:underline">Settings page</Link> and
                disable the platforms you don't use. This speeds up searches and keeps your results
                clean.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Extended FAQ */}
      <section id="faq" className="max-w-2xl w-full scroll-mt-20">
        <h2 className="font-display text-lg font-semibold text-text-primary">
          8. Frequently asked questions
        </h2>
        <div className="mt-4 space-y-4">
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              How do I find where to buy a specific song?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              Paste the track name in Artist - Title format (e.g. "Kerri Chandler - Rain") into the
              search box on the <Link to="/" className="text-accent hover:underline">home page</Link>.
              TrackHunter will search Bandcamp, Beatport, MusicBrainz and Discogs and show you
              direct links to every platform where the track is available.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              Can I import a private Spotify playlist?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              No, only public playlists are supported. To make your playlist public, open it in
              Spotify, click the three dots menu, and select "Make public". Once it's public, copy
              the link and paste it into TrackHunter.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              Why wasn't my track found on a platform?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              Not every track is available on every platform. Independent or niche tracks may only be
              on Bandcamp, while mainstream electronic music is more likely on Beatport. If a track
              isn't found, it may not be available for purchase on that platform, or the title may
              differ slightly between platforms.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              Is my data stored or shared?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              No. TrackHunter runs entirely in your browser. Your playlists and search queries are
              not stored on any server. Your wishlist is saved locally in your browser's storage and
              is never sent anywhere.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              What formats can I upload?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              TrackHunter accepts plain text files (.txt) and CSV files (.csv) with one track per
              line in Artist - Title format. You can also paste track names directly into the search
              box without uploading a file.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              How many tracks can I search at once?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              There's no hard limit. TrackHunter handles playlists of any size. However, very large
              playlists (100+ tracks) will take longer to process since each track is searched across
              multiple platforms. Results appear progressively as they're found.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              Does TrackHunter work on mobile?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              Yes, TrackHunter is fully responsive and works on phones and tablets. You can paste
              playlist links or type track names on any device with a modern browser.
            </p>
          </details>
          <details className="group rounded-sm border border-border bg-bg-secondary">
            <summary className="cursor-pointer px-4 py-3 text-sm font-medium text-text-primary">
              Is TrackHunter free?
            </summary>
            <p className="px-4 pb-3 text-xs text-text-tertiary leading-relaxed">
              Yes, TrackHunter is completely free to use with no account required. There are no
              limitations on the number of searches or tracks. We may display non-intrusive ads to
              help cover hosting costs, but the tool will always remain free.
            </p>
          </details>
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-2xl w-full text-center">
        <div className="rounded-sm border border-border bg-bg-secondary p-6">
          <h2 className="font-display text-lg font-semibold text-text-primary">
            Ready to start?
          </h2>
          <p className="mt-2 text-sm text-text-tertiary">
            Head to the search page and paste your first playlist.
          </p>
          <Link
            to="/"
            className="mt-4 inline-flex items-center gap-2 rounded-sm bg-accent px-6 py-2.5 text-sm font-medium text-text-inverse no-underline transition-colors hover:bg-accent-hover"
          >
            Start searching
          </Link>
        </div>
      </section>
    </div>
  );
}
